### ISSUE TITLE
DB create table scripts

### ISSUE THREAD

**Issue by georgefox6** [GillottandFoxInd/even-freds-happy#3]
It is handy to create a text file containing all of the commands needed to create all of the database tables in case we need to set up a new DB. database commands.txt is located in api/config. Attached an example for reference
![image](https://user-images.githubusercontent.com/18538247/104647552-f3856700-56a9-11eb-82da-c68fee1479df.png)

**Comment by lolamathematician** [comment]
Moved to Ongoing because as table design is refined/new tables are added this will need to always be fixed.
