### ISSUE TITLE
Create the API based on the user example in the repo

### ISSUE THREAD

**Issue by georgefox6** [GillottandFoxInd/even-freds-happy#5]
3 new files need creating for each table:
- api/controllers/[table name].controller.js
- api/models/[table name].model.js
- api/routes/[table name].routes.js

Then the following line needs adding to api/server.js: 
`require("./routes/user.routes.js")(app);`

For the most part you can use the code for user and just use find and replace to change all of the user to the new table name. Just a couple of extra changes are required including changing
 this section in [table].controller.js - 
![image](https://user-images.githubusercontent.com/18538247/104649973-6ba15c00-56ad-11eb-956f-fbbce9e8aa7e.png) ,
This section in [table].model.js - 
![image](https://user-images.githubusercontent.com/18538247/104650081-968bb000-56ad-11eb-89b8-70f4d668ef39.png)

**Comment by lolamathematician** [comment]
All basic API built.
